// examples/workspaces/angular-example/src/app/app.component.ts
import { Component, signal } from '@angular/core'

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <main style="font-family:system-ui;padding:2rem">
      <h1>Hello from Angular in CodingBooth!</h1>
      <p>Click the button to confirm Angular signals work:</p>
      <button (click)="count.update((c) => c + 1)">
        Clicked {{ count() }} time{{ count() === 1 ? '' : 's' }}
      </button>
    </main>
  `,
})
export class AppComponent {
  count = signal(0)
}

// examples/workspaces/react-example/src/App.jsx
import { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)
  return (
    <main style={{ fontFamily: 'system-ui', padding: '2rem' }}>
      <h1>Hello from React in CodingBooth!</h1>
      <p>Click the button to confirm React state works:</p>
      <button onClick={() => setCount((c) => c + 1)}>
        Clicked {count} time{count === 1 ? '' : 's'}
      </button>
    </main>
  )
}
